### ISSUE TITLE
Undocumented use of AWS::RDS::DBSecurityGroup.DBSecurityGroupIngress causes panic

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#27]
Whilst the documentation[1] suggests an array is required in `DBSecurityGroupIngress`, it also supports a map. A template such as this will create successfully in cloudformation:

```
{   
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "test",
  "Resources": {
    "dbsg": {
      "Type": "AWS::RDS::DBSecurityGroup",
      "Properties": {
        "DBSecurityGroupIngress": {     
          "EC2SecurityGroupId": {         
            "Ref": "sg"
          }
        },
        "EC2VpcId": "vpc-xxxxxx",     
        "GroupDescription": "xxx"
      }
    },
    "sg": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
        "VpcId": "vpc-xxxxxx",        
        "GroupDescription": "xxx"
      }
    }
  }
} 
```
And it will result in a panic:

```
panic: interface conversion: interface is map[string]interface {}, not []interface {}

goroutine 1 [running]:
github.com/jagregory/cfval/schema.Schema.Validate(0x1, 0x0, 0x0, 0x0, 0x0, 0x7f75a3707210, 0xc820010310, 0x7f75a37073a8, 0xc82018e940, 0x0, ...)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/schema.go:63 +0x143
github.com/jagregory/cfval/schema.Properties.Validate(0xc8201748d0, 0x7f75a3707a20, 0xc8200870e0, 0x0, 0x0, 0x0, 0x90)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/properties.go:41 +0xa95
github.com/jagregory/cfval/schema.Resource.Validate(0x6a9f20, 0x19, 0x0, 0xc8201748d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/resource.go:18 +0xfa
github.com/jagregory/cfval/schema.resourceValidate(0xc82018f720, 0x19, 0xc820175b30, 0x0, 0x7f75a3707980, 0xc820087050, 0xc820087050, 0x0, 0x0, 0x0)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/template.go:49 +0x284
github.com/jagregory/cfval/schema.TemplateValidate(0xc82018f5c0, 0x7f75a3707950, 0xc820175740, 0x7f75a3707950, 0x0, 0x0, 0x0)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/template.go:15 +0x3c0
main.ValidateCommand.Run(0xc82000a070, 0x0, 0x0, 0xc820173d40)
        /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:174 +0x788
main.(*ValidateCommand).Run(0x7d3c58, 0xc82000a070, 0x0, 0x0, 0x6e2ff0)
        <autogenerated>:6 +0xab
github.com/mitchellh/cli.(*CLI).Run(0xc8200b83c0, 0xc820175830, 0x0, 0x0)
        /home/vagrant/cfval/src/github.com/mitchellh/cli/cli.go:153 +0x538
main.main()
        /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:201 +0x181

goroutine 5 [runnable]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
```

Using `cfval` built from `dba9c5fc82c1dafbe858ad427872e113be8d013e`
```

**Comment by jagregory** [comment]
That's interesting.

Obviously this shouldn't panic... but conceptually should cfval pass
validation? Is it wise to rely on undocumented "features" like this?

The options are:

Pass: this is cool and totally acceptable way to use CF
Warning: this will work, but it's undocumented and theoretically could stop
working.

On Tue, Feb 23, 2016 at 2:42 PM, David Yeung <notifications@github.com>
wrote:

> Whilst the documentation[1] suggests an array is required in
> DBSecurityGroupIngress, it also supports a map. A template such as this
> will create successfully in cloudformation:
>
> {
>   "AWSTemplateFormatVersion": "2010-09-09",
>   "Description": "test",
>   "Resources": {
>     "dbsg": {
>       "Type": "AWS::RDS::DBSecurityGroup",
>       "Properties": {
>         "DBSecurityGroupIngress": {
>           "EC2SecurityGroupId": {
>             "Ref": "sg"
>           }
>         },
>         "EC2VpcId": "vpc-xxxxxx",
>         "GroupDescription": "xxx"
>       }
>     },
>     "sg": {
>       "Type": "AWS::EC2::SecurityGroup",
>       "Properties": {
>         "VpcId": "vpc-xxxxxx",
>         "GroupDescription": "xxx"
>       }
>     }
>   }
> }
>
> And it will result in a panic:
>
> panic: interface conversion: interface is map[string]interface {}, not []interface {}
>
> goroutine 1 [running]:github.com/jagregory/cfval/schema.Schema.Validate(0x1, 0x0, 0x0, 0x0, 0x0, 0x7f75a3707210, 0xc820010310, 0x7f75a37073a8, 0xc82018e940, 0x0, ...)
>         /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/schema.go:63 +0x143github.com/jagregory/cfval/schema.Properties.Validate(0xc8201748d0, 0x7f75a3707a20, 0xc8200870e0, 0x0, 0x0, 0x0, 0x90)
>         /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/properties.go:41 +0xa95github.com/jagregory/cfval/schema.Resource.Validate(0x6a9f20, 0x19, 0x0, 0xc8201748d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/resource.go:18 +0xfagithub.com/jagregory/cfval/schema.resourceValidate(0xc82018f720, 0x19, 0xc820175b30, 0x0, 0x7f75a3707980, 0xc820087050, 0xc820087050, 0x0, 0x0, 0x0)
>         /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/template.go:49 +0x284github.com/jagregory/cfval/schema.TemplateValidate(0xc82018f5c0, 0x7f75a3707950, 0xc820175740, 0x7f75a3707950, 0x0, 0x0, 0x0)
>         /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/template.go:15 +0x3c0
> main.ValidateCommand.Run(0xc82000a070, 0x0, 0x0, 0xc820173d40)
>         /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:174 +0x788
> main.(*ValidateCommand).Run(0x7d3c58, 0xc82000a070, 0x0, 0x0, 0x6e2ff0)
>         <autogenerated>:6 +0xabgithub.com/mitchellh/cli.(*CLI).Run(0xc8200b83c0, 0xc820175830, 0x0, 0x0)
>         /home/vagrant/cfval/src/github.com/mitchellh/cli/cli.go:153 +0x538
> main.main()
>         /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:201 +0x181
>
> goroutine 5 [runnable]:
> os/signal.loop()
>         /usr/lib/go/src/os/signal/signal_unix.go:20
> created by os/signal.init.1
>         /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
>
> Using cfval built from dba9c5fc82c1dafbe858ad427872e113be8d013e
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/cfval/issues/27>.
>



-- 
James Gregory

Tel: 0411619513
Website: http://jagregory.com
Twitter: @jagregory <http://twitter.com/jagregory>

**Comment by yeungda** [comment]
I have a hunch that this uncovers a common behaviour in CloudFormation. When the type is `Array`, it will coerce non-array value `V` into `[V]`.

I would be fine with either pass or warning in this case. Warning might be a bit noisy.

**Comment by jagregory** [comment]
Would a warning convince you to stop using undocumented behaviour and just make the thing an array?

**Comment by yeungda** [comment]
I think CloudFormation would be more likely to document the behaviour than to deprecate it. Whilst it is undocumented, using it bears a risk of confusing the reader. For that reason alone, it's probably worth a Warning.

**Comment by jagregory** [comment]
Fix pushed in d63622abb4a4cab6d8d66d1710f1aa761c3e1464. Until I can decide whether you're wrong to be using CloudFormation like this, failure is the default option with a flag to switch it into warning mode. Let me know if it becomes painful.

```bash
cfval validate -experiment:map-array-coercion <template>

Resources.dbsg.DBSecurityGroupIngress .......................... RDS Security Group Rule used instead of List<RDS Security Group Rule>
Resources.dbsg.DBSecurityGroupIngress.EC2SecurityGroupId.Ref ... Ref value of 'sg' is String but is being dangerously coerced to a SecurityGroupID property

Pass: 0 failures, 2 warnings
```

**Comment by jagregory** [comment]
I'm going to make the experimental flag (warnings for this coercion) the default behaviour until I hear from AWS whether this is something they want to encourage/discourage. Failing seems a bit harsh for something which does appear in the AWS sample templates.

**Comment by jagregory** [comment]
Spoke to AWS, on further investigation this behaviour is exclusive to `DBSecurityGroup` and not intrinsic CloudFormation behaviour. As far as they can tell, `DBSecurityGroupIngress` used to be a single-item property and was later changed to be a list - they've kept both behaviours for backwards compatibility, but prefer people migrate to the list style.

Essentially they deprecated `DBSecurityGroupIngress` and replaced it with a new property with the exact same name.

I'll leave this as a Warning, but AWS's suggestion is to not rely on this behaviour.
