### ISSUE TITLE
RecordSet.Comment should be a property?

### ISSUE THREAD

**Issue by jagregory** [jagregory/cfval#44]
The [docs for RecordSet](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html) don't mention a `Comment` property but the samples include one. The `RecordSet` properties are shared with the nested-resource `RecordSetGroup` whose [property docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordsetgroup.html) do include a `Comment` property. Mystery!

**Comment by yeungda** [comment]
Both links above document `Comment` at the time of writing this.

**Comment by jagregory** [comment]
Sneaky doc update after my chat with them.

On Saturday, 5 March 2016, David Yeung <notifications@github.com> wrote:

> Both links above document Comment at the time of writing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/cfval/issues/44#issuecomment-192623904>.
>


-- 
James Gregory

Tel: 0411619513
Website: http://jagregory.com
Twitter: @jagregory <http://twitter.com/jagregory>
