### ISSUE TITLE
Deep nested Intrinsic Function gets confused with what it's being assigned to

### ISSUE THREAD

**Issue by jagregory** [jagregory/cfval#45]
```json
"ImageId" : { "Fn::FindInMap" : [ "AWSRegionArch2AMI", { "Ref" : "AWS::Region" }, { "Fn::FindInMap" : [ "AWSInstanceType2Arch", { "Ref" : "InstanceType" }, "Arch" ] } ] }
```

In this case, the Ref is being passed a `PropertyContext(ImageId)` and creating a Warning based on a `AWS::Region` not being assignable to an `InstanceId`, when in actual fact the Ref is just being used as a String in a FindInMap.

This can probably be solved by creating a pseudo-property context when a Intrinsic Function is nested.

## Fixed for:

  * [x] Fn::And       
  * [x] Fn::Base64    
  * [x] Fn::Equals    
  * [x] Fn::FindInMap 
  * [x] Fn::GetAtt    
  * [x] Fn::GetAZs    
  * [x] Fn::If        
  * [x] Fn::Join      
  * [x] Fn::Not       
  * [x] Fn::Or        
  * [x] Fn::Select

**Comment by yeungda** [comment]
Another error I'm seeing that seems related to this issue:

template:
```
{
  "Parameters": {
    "subnetIds": {
      "Type": "List<AWS::EC2::Subnet::Id>"
    }
  },
  "Resources": {
    "ElasticacheSubnetGroup": {
      "Type": "AWS::ElastiCache::SubnetGroup",
      "Properties": {
        "Description": ".",
        "SubnetIds": [
         { "Fn::Select": [ 0, { "Ref": "subnetIds" } ] }
        ]
      }
    }
  }
}
```
error:
```
ERROR   Resources.ElasticacheSubnetGroup.SubnetIds.0.Fn::Select.Array.Ref       Ref value of 'subnetIds' is List<SubnetID> but is being assigned to a SubnetID property
```
`cfval` version `e7af583dbdc0f7641678070a176c82a7a9ffe996`

**Comment by jagregory** [comment]
Yep, that's definitely the same thing. The LHS is `SubnetIDs:List<String>`, which gets passed to `Fn::Select` and that naively just passes it down to it's child validations rather than creating a new one representing what it's actually being assigned to (the list argument in this case).
