### ISSUE TITLE
CloudFormation Init service ensureRunning and enabled are Number instead of Bool

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#47]
The [Cloudformation Init services UserGuide](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-services) documents both `ensureRunning` and `enabled` as boolean.

The template:
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "instance": {
      "Type": "AWS::EC2::Instance",
      "Metadata": {
        "AWS::CloudFormation::Init": {
          "foo": {
            "services": {
              "sysvinit": {
                "bar": {
                  "ensureRunning": true,
                  "enabled": true
                }
              }
            }
          }
        }
      }
    }
  }
}
```
Yields these undesired errors:
```
Resources.instance.Metadata.AWS::CloudFormation::Init.foo.services.sysvinit.bar.enabled ......... Value of Bool used in Number property
Resources.instance.Metadata.AWS::CloudFormation::Init.foo.services.sysvinit.bar.ensureRunning ... Value of Bool used in Number property
```
version: `87b495da21cbd389ad5532a2824919a5b674361c`

**Comment by jagregory** [comment]
Weird. Nothing in Metadata should be typed. Thanks

On Saturday, 5 March 2016, David Yeung <notifications@github.com> wrote:

> The Cloudformation Init services UserGuide
> <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-services>
> documents both ensureRunning and enabled as boolean.
>
> The template:
>
> {
>   "AWSTemplateFormatVersion": "2010-09-09",
>   "Resources": {
>     "instance": {
>       "Type": "AWS::EC2::Instance",
>       "Metadata": {
>         "AWS::CloudFormation::Init": {
>           "foo": {
>             "services": {
>               "sysvinit": {
>                 "bar": {
>                   "ensureRunning": true,
>                   "enabled": true
>                 }
>               }
>             }
>           }
>         }
>       }
>     }
>   }
> }
>
> Yields these undesired errors:
>
> Resources.instance.Metadata.AWS::CloudFormation::Init.foo.services.sysvinit.bar.enabled ......... Value of Bool used in Number property
> Resources.instance.Metadata.AWS::CloudFormation::Init.foo.services.sysvinit.bar.ensureRunning ... Value of Bool used in Number property
>
> version: 87b495da21cbd389ad5532a2824919a5b674361c
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/cfval/issues/47>.
>


-- 
James Gregory

Tel: 0411619513
Website: http://jagregory.com
Twitter: @jagregory <http://twitter.com/jagregory>
