### ISSUE TITLE
Using String for Index in Select is an Error

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#49]
template:

```
{
  "Parameters": {
    "subnetIds": {
      "Type": "List<AWS::EC2::Subnet::Id>"
    }
  },
  "Resources": {
    "ElasticacheSubnetGroup": {
      "Type": "AWS::ElastiCache::SubnetGroup",
      "Properties": {
        "Description": ".",
        "SubnetIds": [
         { "Fn::Select": [ "0", { "Ref": "subnetIds" } ] }
        ]
      }
    }
  }
}
```
yields error:
```
ERROR   Resources.ElasticacheSubnetGroup.SubnetIds.0.Fn::Select.Index   Wrong type for index string
```

using `cfval` version `e7af583dbdc0f7641678070a176c82a7a9ffe996`.

Dangerous coersions seem to usually be warnings, so the only thing that seems out of place to me here is that this is reported as an error.

**Comment by jagregory** [comment]
Ideally, I would like to implement #37 and be able to run validations on the index even if it is a string; however, until then I agree this should be a warning.
