### ISSUE TITLE
AWS::S3::BucketPolicy.PolicyDocument.Statement.i.Condition not valid

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#51]
This [doc](http://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html) confirms the `Condition` property in bucket policy statements. `cfval` reports an error when it is used.

template:
```
{
  "Resources": {
    "BucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [ "s3:*" ],
              "Resource": [ "arn:aws:s3:::foo" ],
              "Effect": "Allow",
              "Condition": {
                "IpAddress": { "aws:SourceIp": [ "127.0.0.1/32" ] }
              },
              "Principal": { "AWS": "*" }
            }
          ]
        },
        "Bucket": "foo"
      }
    }
  }
}
```
output:
```
ERROR   Resources.BucketPolicy.PolicyDocument.Statement.0       Condition not valid in this location
```
version: `e7af583dbdc0f7641678070a176c82a7a9ffe996`

**Comment by jagregory** [comment]
Ah, this is because I introduced some awareness of conditions in #28 for the `Fn::If`-style functions; unfortunately, that's introduced this error because it now tries to parse them. I either need to hurry up and get #6 done, or downgrade this to a warning until it is implemented.
