### ISSUE TITLE
AWS::ElastiCache::CacheCluster.CacheSubnetGroupName conflicts with VpcSecurityGroupIds

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#52]
It seems `cfval` errors when both [`CacheSubnetGroupName`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#cfn-elasticache-cachecluster-cachesubnetgroupname) and `VpcSecurityGroupIds` are present. I can't see any relationship between these in the docs. They do specify a relationship between `VpcSecurityGroupIds` and [`CacheSecurityGroupNames`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#cfn-elasticache-cachecluster-cachesecuritygroupnames), so perhaps this was mistakenly applied to the wrong property pair?

template:
```
{
  "Resources": {
    "foo": {
      "Type": "AWS::ElastiCache::CacheCluster",
      "Properties": {
        "Engine": "redis",
        "NumCacheNodes": 1,
        "VpcSecurityGroupIds": [ "sg-abcdefgh" ],
        "ClusterName": "foo",
        "CacheSubnetGroupName": "foo",
        "CacheNodeType": "cache.m1.small"
      }
    }
  }
}
```
version: `e7af583dbdc0f7641678070a176c82a7a9ffe996`
output:
```
Resources.foo.CacheSubnetGroupName ... Conflict: VpcSecurityGroupIds exists
```

**Comment by jagregory** [comment]
Yeah, that looks like a mistake.
