### ISSUE TITLE
AWS::S3::BucketPolicy.PolicyDocument.Statement.i.Principal.AWS cannot be List<String>

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#53]
The [bucket policy documentation for principals](http://docs.aws.amazon.com/AmazonS3/latest/dev/s3-bucket-user-policy-specifying-principal-intro.html) links to the [Principal in the IAM Policy guide](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Principal), which gives examples of the key `"AWS"` can be of type `String` or `List<String>`. `cfval` does not allow refs of type `List<String>` to be assigned.

template:
```
{
  "Parameters": {
    "foo": {
      "Type": "CommaDelimitedList"
    }
  },
  "Resources": {
    "BucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [ "s3:*" ],
              "Resource": [ "arn:aws:s3:::foo" ],
              "Effect": "Allow",
              "Principal": {
                "AWS": {
                  "Ref": "foo"
                }
              }
            }
          ]
        },
        "Bucket": "foo"
      }
    }
  }
}
```
output:
```
ERROR   Resources.BucketPolicy.PolicyDocument.Statement.0.Principal.AWS.Ref     Ref value of 'foo' is List<String> but is being assigned to a String property
```
version: `e7af583dbdc0f7641678070a176c82a7a9ffe996`

**Comment by jagregory** [comment]
Ah, interesting. Thanks.

I think this is another flaw in the JSON validation. It defaults to a String as the LHS, which seems to only really be used when a function is called. I've seen a couple of other places like this which could probably benefit from some kind of Any type.
